### ISSUE TITLE
Error while amending Material Request for Purchase

### ISSUE THREAD

**Issue by cgpurbaugh** [cgpurbaugh/metalcraft#7]
jquery.min.js:4 POST https://erp.sea-fire.com/ 500 (INTERNAL SERVER ERROR)
send @ jquery.min.js:4
ajax @ jquery.min.js:4
frappe.request.call @ request.js:199
frappe.call @ request.js:77
p @ save.js:191
frappe.ui.form.save @ save.js:25
(anonymous) @ form.js:755
Promise.then (async)
(anonymous) @ dom.js:249
frappe.run_serially @ dom.js:247
_f.Frm._save @ form.js:746
(anonymous) @ form.js:700
setTimeout (async)
(anonymous) @ form.js:699
_f.Frm.save @ form.js:693
Save @ toolbar.js:303
(anonymous) @ page.js:160
dispatch @ jquery.min.js:3
r.handle @ jquery.min.js:3
request.js:321 Traceback (most recent call last):
  File "/home/virtual/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
    doc.save()
  File "/home/virtual/frappe-bench/apps/frappe/frappe/model/document.py", line 260, in save
    return self._save(*args, **kwargs)
  File "/home/virtual/frappe-bench/apps/frappe/frappe/model/document.py", line 283, in _save
    self.insert()
  File "/home/virtual/frappe-bench/apps/frappe/frappe/model/document.py", line 222, in insert
    self.run_before_save_methods()
  File "/home/virtual/frappe-bench/apps/frappe/frappe/model/document.py", line 876, in run_before_save_methods
    self.run_method("validate")
  File "/home/virtual/frappe-bench/apps/frappe/frappe/model/document.py", line 772, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/virtual/frappe-bench/apps/frappe/frappe/model/document.py", line 1048, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/virtual/frappe-bench/apps/frappe/frappe/model/document.py", line 1031, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/virtual/frappe-bench/apps/frappe/frappe/model/document.py", line 766, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/virtual/frappe-bench/apps/erpnext/erpnext/stock/doctype/material_request/material_request.py", line 62, in validate
    super(MaterialRequest, self).validate()
  File "/home/virtual/frappe-bench/apps/erpnext/erpnext/controllers/buying_controller.py", line 38, in validate
    super(BuyingController, self).validate()
  File "/home/virtual/frappe-bench/apps/erpnext/erpnext/controllers/stock_controller.py", line 21, in validate
    super(StockController, self).validate()
  File "/home/virtual/frappe-bench/apps/erpnext/erpnext/controllers/accounts_controller.py", line 63, in validate
    self.set_missing_values(for_validate=True)
  File "/home/virtual/frappe-bench/apps/erpnext/erpnext/controllers/buying_controller.py", line 74, in set_missing_values
    doctype=self.doctype, company=self.company, party_address=self.supplier_address, shipping_address=self.get('shipping_address')))
AttributeError: 'MaterialRequest' object has no attribute 'supplier_address'

request.js:321 Traceback (most recent call last):
  File "/home/virtual/frappe-bench/apps/frappe/frappe/app.py", line 61, in application
    response = frappe.handler.handle()
  File "/home/virtual/frappe-bench/apps/frappe/frappe/handler.py", line 21, in handle
    data = execute_cmd(cmd)
  File "/home/virtual/frappe-bench/apps/frappe/frappe/handler.py", line 56, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/virtual/frappe-bench/apps/frappe/frappe/__init__.py", line 1030, in call
    return fn(*args, **newargs)
  File "/home/virtual/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
    doc.save()
  File "/home/virtual/frappe-bench/apps/frappe/frappe/model/document.py", line 260, in save
    return self._save(*args, **kwargs)
  File "/home/virtual/frappe-bench/apps/frappe/frappe/model/document.py", line 283, in _save
    self.insert()
  File "/home/virtual/frappe-bench/apps/frappe/frappe/model/document.py", line 222, in insert
    self.run_before_save_methods()
  File "/home/virtual/frappe-bench/apps/frappe/frappe/model/document.py", line 876, in run_before_save_methods
    self.run_method("validate")
  File "/home/virtual/frappe-bench/apps/frappe/frappe/model/document.py", line 772, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/virtual/frappe-bench/apps/frappe/frappe/model/document.py", line 1048, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/virtual/frappe-bench/apps/frappe/frappe/model/document.py", line 1031, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/virtual/frappe-bench/apps/frappe/frappe/model/document.py", line 766, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/virtual/frappe-bench/apps/erpnext/erpnext/stock/doctype/material_request/material_request.py", line 62, in validate
    super(MaterialRequest, self).validate()
  File "/home/virtual/frappe-bench/apps/erpnext/erpnext/controllers/buying_controller.py", line 38, in validate
    super(BuyingController, self).validate()
  File "/home/virtual/frappe-bench/apps/erpnext/erpnext/controllers/stock_controller.py", line 21, in validate
    super(StockController, self).validate()
  File "/home/virtual/frappe-bench/apps/erpnext/erpnext/controllers/accounts_controller.py", line 63, in validate
    self.set_missing_values(for_validate=True)
  File "/home/virtual/frappe-bench/apps/erpnext/erpnext/controllers/buying_controller.py", line 74, in set_missing_values
    doctype=self.doctype, company=self.company, party_address=self.supplier_address, shipping_address=self.get('shipping_address')))
AttributeError: 'MaterialRequest' object has no attribute 'supplier_address'

**Comment by cgpurbaugh** [comment]
Fixed with custom field.
